spring:
  redis:
    host: 192.168.89.128
    port: 6379
    database: 0
    connect-timeout: 1800000
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
    password: passerby159lzf
